In [65]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from sklearn import linear_model
%matplotlib inline
pd.options.display.float_format = '{:.3f}'.format

# Suppress annoying harmless error.
import warnings
warnings.filterwarnings(action="ignore", module="scipy", message="^internal gelsd")

In [74]:
crime = pd.read_excel("reg multi.xlsx")
crime

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition)1,Rape (legacy definition)2,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft,Arson3
0,Adams Village,1861.000,0.000,0.000,nan,0.000,0.000,0.000,12.000,2.000,10.000,0.000,0.000
1,Addison Town and Village,2577.000,3.000,0.000,nan,0.000,0.000,3.000,24.000,3.000,20.000,1.000,0.000
2,Akron Village,2846.000,3.000,0.000,nan,0.000,0.000,3.000,16.000,1.000,15.000,0.000,0.000
3,Albany,97956.000,791.000,8.000,nan,30.000,227.000,526.000,4090.000,705.000,3243.000,142.000,nan
4,Albion Village,6388.000,23.000,0.000,nan,3.000,4.000,16.000,223.000,53.000,165.000,5.000,nan
5,Alfred Village,4089.000,5.000,0.000,nan,0.000,3.000,2.000,46.000,10.000,36.000,0.000,nan
6,Allegany Village,1781.000,3.000,0.000,nan,0.000,0.000,3.000,10.000,0.000,10.000,0.000,0.000
7,Amherst Town,118296.000,107.000,1.000,nan,7.000,31.000,68.000,2118.000,204.000,1882.000,32.000,3.000
8,Amityville Village,9519.000,9.000,0.000,nan,2.000,4.000,3.000,210.000,16.000,188.000,6.000,1.000
9,Amsterdam,18182.000,30.000,0.000,nan,0.000,12.000,18.000,405.000,99.000,291.000,15.000,0.000
10,Arcade Village,2053.000,0.000,0.000,nan,0.000,0.000,0.000,39.000,3.000,35.000,1.000,0.000
11,Ardsley Village,4523.000,5.000,0.000,nan,0.000,3.000,2.000,33.000,4.000,28.000,1.000,0.000
12,Asharoken Village,658.000,0.000,0.000,nan,0.000,0.000,0.000,2.000,0.000,2.000,0.000,0.000
13,Attica Village,2522.000,2.000,0.000,nan,0.000,0.000,2.000,5.000,0.000,4.000,1.000,0.000
14,Auburn,27270.000,96.000,1.000,nan,20.000,22.000,53.000,859.000,132.000,721.000,6.000,nan
15,Avon Village,3333.000,1.000,0.000,nan,0.000,1.000,0.000,25.000,3.000,20.000,2.000,nan
16,Baldwinsville Village,7473.000,5.000,0.000,nan,0.000,1.000,4.000,88.000,10.000,77.000,1.000,0.000
17,Ballston Spa Village,5418.000,8.000,0.000,nan,0.000,3.000,5.000,94.000,16.000,78.000,0.000,1.000
18,Batavia,15374.000,57.000,0.000,nan,7.000,13.000,37.000,559.000,103.000,454.000,2.000,nan
19,Bath Village,5733.000,15.000,0.000,nan,1.000,3.000,11.000,191.000,32.000,157.000,2.000,2.000
20,Bedford Town,17627.000,5.000,0.000,nan,0.000,1.000,4.000,156.000,26.000,127.000,3.000,nan
21,Bethlehem Town,34243.000,13.000,0.000,nan,0.000,3.000,10.000,442.000,50.000,388.000,4.000,nan
22,Binghamton,46304.000,284.000,3.000,nan,19.000,101.000,161.000,2349.000,525.000,1767.000,57.000,nan
23,Black River,1410.000,0.000,0.000,nan,0.000,0.000,0.000,14.000,2.000,12.000,0.000,0.000
24,Blooming Grove Town,12001.000,8.000,0.000,nan,1.000,0.000,7.000,99.000,20.000,72.000,7.000,nan
25,Bolivar Village,1022.000,1.000,0.000,nan,0.000,0.000,1.000,4.000,2.000,2.000,0.000,0.000
26,Bolton Town,2325.000,2.000,0.000,nan,0.000,0.000,2.000,24.000,4.000,20.000,0.000,0.000
27,Boonville Village,2054.000,1.000,0.000,nan,0.000,0.000,1.000,20.000,6.000,14.000,0.000,0.000
28,Brant Town,2065.000,4.000,0.000,nan,0.000,1.000,3.000,31.000,9.000,20.000,2.000,0.000
29,Brewster,2358.000,0.000,0.000,nan,0.000,0.000,0.000,13.000,3.000,10.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,Tuxedo Park Village,615.000,0.000,0.000,nan,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
320,Ulster Town,12195.000,14.000,0.000,nan,3.000,2.000,9.000,437.000,25.000,410.000,2.000,nan
321,Utica,61686.000,361.000,7.000,nan,27.000,102.000,225.000,2528.000,449.000,1997.000,82.000,nan
322,Vestal Town,27980.000,16.000,0.000,nan,2.000,6.000,8.000,571.000,39.000,523.000,9.000,nan
323,Walden Village,6887.000,18.000,1.000,nan,2.000,1.000,14.000,142.000,13.000,124.000,5.000,nan
324,Wallkill Town,27940.000,40.000,0.000,nan,3.000,16.000,21.000,767.000,91.000,650.000,26.000,1.000
325,Walton Village,3012.000,6.000,0.000,nan,1.000,0.000,5.000,68.000,18.000,50.000,0.000,nan
326,Warsaw Village,3453.000,6.000,0.000,nan,1.000,0.000,5.000,78.000,5.000,73.000,0.000,0.000
327,Washingtonville Village,5828.000,2.000,0.000,nan,0.000,1.000,1.000,58.000,5.000,51.000,2.000,0.000
328,Waterford Town and Village,8392.000,4.000,0.000,nan,0.000,0.000,4.000,59.000,6.000,52.000,1.000,0.000
329,Waterloo Village,5175.000,11.000,0.000,nan,0.000,3.000,8.000,194.000,23.000,169.000,2.000,nan
330,Watertown,28179.000,109.000,0.000,nan,12.000,16.000,81.000,1165.000,169.000,953.000,43.000,nan
331,Watervliet,10245.000,26.000,1.000,nan,3.000,11.000,11.000,242.000,58.000,163.000,21.000,nan
332,Watkins Glen Village,1862.000,6.000,0.000,nan,0.000,0.000,6.000,92.000,10.000,80.000,2.000,nan
333,Waverly Village,4337.000,5.000,0.000,nan,0.000,1.000,4.000,54.000,9.000,41.000,4.000,nan
334,Webster Town and Village,43777.000,21.000,0.000,nan,2.000,3.000,16.000,469.000,101.000,361.000,7.000,nan
335,Weedsport Village,1797.000,0.000,0.000,nan,0.000,0.000,0.000,25.000,5.000,20.000,0.000,0.000
336,Wellsville Village,4574.000,11.000,0.000,nan,1.000,0.000,10.000,164.000,32.000,129.000,3.000,1.000
337,Westhampton Beach Village,1732.000,2.000,0.000,nan,0.000,0.000,2.000,44.000,4.000,37.000,3.000,0.000
338,West Seneca Town,44821.000,35.000,1.000,nan,1.000,9.000,24.000,896.000,166.000,710.000,20.000,0.000
339,Whitehall Village,2604.000,6.000,0.000,nan,0.000,0.000,6.000,62.000,12.000,49.000,1.000,nan
340,White Plains,57559.000,78.000,1.000,nan,3.000,28.000,46.000,1232.000,77.000,1134.000,21.000,nan
341,Whitesboro Village,3733.000,4.000,0.000,nan,0.000,0.000,4.000,36.000,14.000,21.000,1.000,0.000
342,Whitestown Town,9141.000,0.000,0.000,nan,0.000,0.000,0.000,77.000,13.000,61.000,3.000,0.000
343,Woodbury Town,10685.000,3.000,0.000,nan,0.000,2.000,1.000,541.000,9.000,529.000,3.000,nan
344,Woodridge Village,829.000,7.000,0.000,nan,0.000,0.000,7.000,17.000,8.000,9.000,0.000,0.000
345,Woodstock Town,5931.000,2.000,0.000,nan,0.000,0.000,2.000,58.000,13.000,45.000,0.000,nan
346,Yonkers,199134.000,1036.000,6.000,nan,25.000,390.000,615.000,2368.000,470.000,1662.000,236.000,10.000
347,Yorktown Town,36643.000,15.000,0.000,nan,0.000,2.000,13.000,334.000,45.000,287.000,2.000,nan
348,NaN,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan,nan

In [75]:
crime['Pop2'] = crime["Population"]**2
crime['Pop2'].head(5)

0      3463321.000
1      6640929.000
2      8099716.000
3   9595377936.000
4     40806544.000
Name: Pop2, dtype: float64

In [82]:
crime['Murder and\nnonnegligent\nmanslaughter']= crime['Murder and\nnonnegligent\nmanslaughter'].astype('int')

crime.dtypes

City                                        object
Population                                 float64
Violent\ncrime                             float64
Murder and\nnonnegligent\nmanslaughter       int32
Rape\n(revised\ndefinition)1               float64
Rape\n(legacy\ndefinition)2                float64
Robbery                                    float64
Aggravated\nassault                        float64
Property\ncrime                            float64
Burglary                                   float64
Larceny-\ntheft                            float64
Motor\nvehicle\ntheft                      float64
Arson3                                     float64
Pop2                                       float64
Murder                                    category
Rob                                          int32
dtype: object

In [83]:
crime['Murder']= crime['Murder and\nnonnegligent\nmanslaughter']
crime['Murder'].head(5)

0    0
1    0
2    0
3    8
4    0
Name: Murder, dtype: int32

In [84]:

crime['Murd']=np.where(crime['Murder']>0, 1, 0)
crime.head(10)

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition)1,Rape (legacy definition)2,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft,Arson3,Pop2,Murder,Rob,Murd
0,Adams Village,1861.000,0.000,0,nan,0.000,0.000,0.000,12.000,2.000,10.000,0.000,0.000,3463321.000,0,0,0
1,Addison Town and Village,2577.000,3.000,0,nan,0.000,0.000,3.000,24.000,3.000,20.000,1.000,0.000,6640929.000,0,0,0
2,Akron Village,2846.000,3.000,0,nan,0.000,0.000,3.000,16.000,1.000,15.000,0.000,0.000,8099716.000,0,0,0
3,Albany,97956.000,791.000,8,nan,30.000,227.000,526.000,4090.000,705.000,3243.000,142.000,nan,9595377936.000,8,1,1
4,Albion Village,6388.000,23.000,0,nan,3.000,4.000,16.000,223.000,53.000,165.000,5.000,nan,40806544.000,0,1,0
5,Alfred Village,4089.000,5.000,0,nan,0.000,3.000,2.000,46.000,10.000,36.000,0.000,nan,16719921.000,0,1,0
6,Allegany Village,1781.000,3.000,0,nan,0.000,0.000,3.000,10.000,0.000,10.000,0.000,0.000,3171961.000,0,0,0
7,Amherst Town,118296.000,107.000,1,nan,7.000,31.000,68.000,2118.000,204.000,1882.000,32.000,3.000,13993943616.000,1,1,1
8,Amityville Village,9519.000,9.000,0,nan,2.000,4.000,3.000,210.000,16.000,188.000,6.000,1.000,90611361.000,0,1,0
9,Amsterdam,18182.000,30.000,0,nan,0.000,12.000,18.000,405.000,99.000,291.000,15.000,0.000,330585124.000,0,1,0

In [85]:
crime['Robbery']= crime['Robbery'].astype('int')

ValueError: Cannot convert non-finite values (NA or inf) to integer

In [80]:

crime['Rob']=np.where(crime['Robbery']>0, 1, 0)
crime.head(10)

,City,Population,Violent crime,Murder and nonnegligent manslaughter,Rape (revised definition)1,Rape (legacy definition)2,Robbery,Aggravated assault,Property crime,Burglary,Larceny- theft,Motor vehicle theft,Arson3,Pop2,Murder,Rob
0,Adams Village,1861.000,0.000,0.000,nan,0.000,0.000,0.000,12.000,2.000,10.000,0.000,0.000,3463321.000,0.000,0
1,Addison Town and Village,2577.000,3.000,0.000,nan,0.000,0.000,3.000,24.000,3.000,20.000,1.000,0.000,6640929.000,0.000,0
2,Akron Village,2846.000,3.000,0.000,nan,0.000,0.000,3.000,16.000,1.000,15.000,0.000,0.000,8099716.000,0.000,0
3,Albany,97956.000,791.000,8.000,nan,30.000,227.000,526.000,4090.000,705.000,3243.000,142.000,nan,9595377936.000,8.000,1
4,Albion Village,6388.000,23.000,0.000,nan,3.000,4.000,16.000,223.000,53.000,165.000,5.000,nan,40806544.000,0.000,1
5,Alfred Village,4089.000,5.000,0.000,nan,0.000,3.000,2.000,46.000,10.000,36.000,0.000,nan,16719921.000,0.000,1
6,Allegany Village,1781.000,3.000,0.000,nan,0.000,0.000,3.000,10.000,0.000,10.000,0.000,0.000,3171961.000,0.000,0
7,Amherst Town,118296.000,107.000,1.000,nan,7.000,31.000,68.000,2118.000,204.000,1882.000,32.000,3.000,13993943616.000,1.000,1
8,Amityville Village,9519.000,9.000,0.000,nan,2.000,4.000,3.000,210.000,16.000,188.000,6.000,1.000,90611361.000,0.000,1
9,Amsterdam,18182.000,30.000,0.000,nan,0.000,12.000,18.000,405.000,99.000,291.000,15.000,0.000,330585124.000,0.000,1

In [86]:
Propertycrime = crime[['City','Population','Pop2','Murd','Rob']]
Propertycrime

                           City  Population            Pop2  Murd  Rob
0                 Adams Village    1861.000     3463321.000     0    0
1      Addison Town and Village    2577.000     6640929.000     0    0
2                 Akron Village    2846.000     8099716.000     0    0
3                        Albany   97956.000  9595377936.000     1    1
4                Albion Village    6388.000    40806544.000     0    1
5                Alfred Village    4089.000    16719921.000     0    1
6              Allegany Village    1781.000     3171961.000     0    0
7                  Amherst Town  118296.000 13993943616.000     1    1
8            Amityville Village    9519.000    90611361.000     0    1
9                     Amsterdam   18182.000   330585124.000     0    1
10               Arcade Village    2053.000     4214809.000     0    0
11              Ardsley Village    4523.000    20457529.000     0    1
12            Asharoken Village     658.000      432964.000     0    0
13               Attica Village    2522.000     6360484.000     0    0
14                       Auburn   27270.000   743652900.000     1    1
15                 Avon Village    3333.000    11108889.000     0    1
16        Baldwinsville Village    7473.000    55845729.000     0    1
17         Ballston Spa Village    5418.000    29354724.000     0    1
18                      Batavia   15374.000   236359876.000     0    1
19                 Bath Village    5733.000    32867289.000     0    1
20                 Bedford Town   17627.000   310711129.000     0    1
21               Bethlehem Town   34243.000  1172583049.000     0    1
22                   Binghamton   46304.000  2144060416.000     1    1
23                  Black River    1410.000     1988100.000     0    0
24          Blooming Grove Town   12001.000   144024001.000     0    0
25              Bolivar Village    1022.000     1044484.000     0    0
26                  Bolton Town    2325.000     5405625.000     0    0
27            Boonville Village    2054.000     4218916.000     0    0
28                   Brant Town    2065.000     4264225.000     0    1
29                     Brewster    2358.000     5560164.000     0    0
..                          ...         ...             ...   ...  ...
319         Tuxedo Park Village     615.000      378225.000     0    0
320                 Ulster Town   12195.000   148718025.000     0    1
321                       Utica   61686.000  3805162596.000     1    1
322                 Vestal Town   27980.000   782880400.000     0    1
323              Walden Village    6887.000    47430769.000     1    1
324               Wallkill Town   27940.000   780643600.000     0    1
325              Walton Village    3012.000     9072144.000     0    0
326              Warsaw Village    3453.000    11923209.000     0    0
327     Washingtonville Village    5828.000    33965584.000     0    1
328  Waterford Town and Village    8392.000    70425664.000     0    0
329            Waterloo Village    5175.000    26780625.000     0    1
330                   Watertown   28179.000   794056041.000     0    1
331                  Watervliet   10245.000   104960025.000     1    1
332        Watkins Glen Village    1862.000     3467044.000     0    0
333             Waverly Village    4337.000    18809569.000     0    1
334    Webster Town and Village   43777.000  1916425729.000     0    1
335           Weedsport Village    1797.000     3229209.000     0    0
336          Wellsville Village    4574.000    20921476.000     0    0
337   Westhampton Beach Village    1732.000     2999824.000     0    0
338            West Seneca Town   44821.000  2008922041.000     1    1
339           Whitehall Village    2604.000     6780816.000     0    0
340                White Plains   57559.000  3313038481.000     1    1
341          Whitesboro Village    3733.000    13935289.000     0    0
342             Whitestown Town    9141.000    83557881.000     0    0
343               Woodbury Town   10685.000   114169225.000     0    1
344           Woodridge Village     829.000      687241.000     0    0
345              Woodstock Town    5931.000    35176761.000     0    0
346                     Yonkers  199134.000 39654349956.000     1    1
347               Yorktown Town   36643.000  1342709449.000     0    1
348                         NaN         nan             nan     0    0

[349 rows x 5 columns]