In [17]:

class CustomKNN:

    #constructor

    def __init__(self):

            self.accurate_predictions = 0

            self.total_predictions = 0

            self.accuracy = 0.0

In [18]:
import pandas as pd

In [23]:
df = pd.read_csv("chronic_kidney_disease.csv") #Reading from the data file
df.head(5)

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wbcc,rbcc,htn,dm,cad,appet,pe,ane,class
0,48,80,1.020,1,0,?,normal,notpresent,notpresent,121,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,7,50,1.020,4,0,?,normal,notpresent,notpresent,?,...,38,6000,?,no,no,no,good,no,no,ckd
2,62,80,1.010,2,3,normal,normal,notpresent,notpresent,423,...,31,7500,?,no,yes,no,poor,no,yes,ckd
3,48,70,1.005,4,0,normal,abnormal,present,notpresent,117,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,51,80,1.010,2,0,normal,normal,notpresent,notpresent,106,...,35,7300,4.6,no,no,no,good,no,no,ckd

In [24]:
def mod_data(df):

    df.replace('?', -999999, inplace = True)

    df.replace('yes', 4, inplace = True)

    df.replace('no', 2, inplace = True)

    df.replace('notpresent', 4, inplace = True)

    df.replace('present', 2, inplace = True)

    df.replace('abnormal', 4, inplace = True)

    df.replace('normal', 2, inplace = True)

    df.replace('poor', 4, inplace = True)

    df.replace('good', 2, inplace = True)

    df.replace('ckd', 4, inplace = True)

    df.replace('notckd', 2, inplace = True)

In [31]:

mod_data(df)

dataset = df.astype(float).values.tolist()

    #Shuffle the dataset

import random as random
random.shuffle(dataset) #import random for this

In [32]:
#25% of the available data will be used for testing

test_size = 0.25

#The keys of the dict are the classes that the data is classfied into

training_set = {2: [], 4:[]}

test_set = {2: [], 4:[]}

In [34]:
#Split data into training and test for cross validation

training_data = dataset[:-int(test_size \* len(dataset))]

test_data = dataset[-int(test_size \* len(dataset)):]

#Insert data into the training set
for record in training_data:
#Append the list in the dict will all the elements of the record except the class
training_set[record[-1]].append(record[:-1]) 

#Insert data into the test set

for record in test_data:
# Append the list in the dict will all the elements of the record except the class
test_set[record[-1]].append(record[:-1])

SyntaxError: unexpected character after line continuation character (<ipython-input-34-4d254c4102a9>, line 3)

In [35]:
import math

def Euclidean_distance(feat_one, feat_two):

    squared_distance = 0

    #Assuming correct input to the function where the lengths of two features are the same

    for i in range(len(feat_one)):

            squared_distance += (feat_one[i] â€“ feat_two[i])**2

    ed = sqrt(squared_distances)

    return ed;

SyntaxError: invalid character in identifier (<ipython-input-35-cf77b28579e3>, line 11)